In [5]:
!pip install numpy --upgrade

Requirement already up-to-date: numpy in c:\users\aouatef-pc\appdata\local\programs\python\python37-32\lib\site-packages (1.16.2)


In [5]:
import numpy as np

In [6]:
array_one=np.array([1,2,3,4]) #create an array
array_one #call the created array

array([1, 2, 3, 4])

In [7]:
numbers=[9,8,7,6] #declare an array
array_two=np.array(numbers) #create an array
array_two #call the created array

array([9, 8, 7, 6])

In [8]:
#function zeros 
#quit way to initialise an array in order to use it in other calculation
array_of_zeroes = np.zeros((3,4)) #initialise an array to have all element equal to 0
array_of_zeroes

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
#function ones 
# createan array with the shape that we specify and initialises all the element to 1
array_of_ones = np.ones((3,4))
array_of_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
#Use dtype in order to specify the data type
array_of_ones_int = np.ones((3,4),dtype=np.int16)
array_of_ones_int

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [11]:
# setup an empty array without initialisation
array_empty=np.empty((2,3))
array_empty

array([[2.67276450e+185, 1.69506143e+190, 1.75184137e+190],
       [9.48819320e+077, 1.63730399e-306, 0.00000000e+000]])

In [12]:
#creates an eyedentity matrix
array_eye = np.eye(3)
array_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
#To create sequences of numbers, NumPy provides a function analogous to range that returns arrays instead of lists
array_of_events=np.arange(2, 20, 2)
array_of_events

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
#It also accepts float arguments
array_of_floats = np.arange( 0, 2, 0.3)
array_of_floats

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [15]:
#Two Dimensional Arrays
array_2d = np.array([(2,4,6),(3,5,7)]) 
array_2d

array([[2, 4, 6],
       [3, 5, 7]])

In [16]:
#show the shape of the array
array_2d.shape

(2, 3)

In [17]:
#Using reshape to create n dimensional arrays
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [18]:
array_nd = np.arange(6).reshape(3,2) 
array_nd

array([[0, 1],
       [2, 3],
       [4, 5]])

In [19]:
#Produce an array of all 1’s with the given shape and dtype
array_ones = np.ones_like(array_nd)
array_ones

array([[1, 1],
       [1, 1],
       [1, 1]])