In [1]:
import numpy as np

In [2]:
# NumPy operations are usually done on pairs of arrays on an element-by-element basis. In the simplest case, the two arrays must have exactly the same shape, as in the following example:

In [3]:
a = np.array([1,2,3,4,5])
b = np.array([10,10,10,10,10])

In [4]:
a * b

array([10, 20, 30, 40, 50])

In [5]:
c=10

In [7]:
a * c

array([10, 20, 30, 40, 50])

In [11]:
one = np.ones((4,3))

In [12]:
one * c

array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])

In [13]:
heights  = [165,170,168,183,172,169]
weights  = [61,76,56,81,62,60]

In [14]:
student_bio = np.array([heights,weights])

In [15]:
student_bio

array([[165, 170, 168, 183, 172, 169],
       [ 61,  76,  56,  81,  62,  60]])

In [16]:
# Now, we would like to convert heights into feet and weights into kilograms, for that the conversion factors are 0.0328084 and 2.20462 respectively

In [17]:
factor_1 = np.array([0.0328084,2.20462 ])

In [18]:
factor_1

array([0.0328084, 2.20462  ])

In [21]:
factor_1.shape

(2,)

In [22]:
student_bio.shape

(2, 6)

In [24]:
# Shape mismatch
# This fails because there is a mismatch in the trailing dimensions 
# student bio: 2 x 6 
# factor_1:            2

# The trailing dimensions here are 6 and 2, so there is a mismatch
factor_1 * student_bio

ValueError: operands could not be broadcast together with shapes (2,) (2,6) 

In [25]:
factor_2 = np.array([[0.0328084],[2.20462 ]])

In [26]:
factor_2

array([[0.0328084],
       [2.20462  ]])

In [27]:
factor_2.shape

(2, 1)

In [28]:
student_bio * factor_2

array([[  5.413386 ,   5.577428 ,   5.5118112,   6.0039372,   5.6430448,
          5.5446196],
       [134.48182  , 167.55112  , 123.45872  , 178.57422  , 136.68644  ,
        132.2772   ]])