In [1]:
#When we index arrays with arrays of (integer) indices we are providing the list of indices to pick. With boolean indices the approach is different; we explicitly choose which items in the array we want and which ones we don’t.
#Frequently this type of indexing is used to select the elements of an array that satisfy some condition

In [2]:
import numpy as np

In [4]:
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [5]:
#Now we find the elements that are greater than 9. This will return a numpy array of the same shape as our original array. 

In [6]:
indx_bool = a > 9

In [7]:
indx_bool

array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [12]:
a[indx_bool]

array([10, 11, 12, 13, 14, 15])

In [13]:
#We can do all of the above in a single concise statement
a[a > 9]

array([10, 11, 12, 13, 14, 15])

In [14]:
#How many values less than 6?
a < 6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [15]:
np.count_nonzero(a < 6)

6

In [16]:
np.sum(a < 6)

6

In [17]:
#How many values less than 6 in each row?
np.sum(a <6 , axis=1)

array([4, 2, 0, 0])

In [18]:
#Are there any values greater than 8?
np.any(a >8)

True

In [19]:
#Are all values less than 10?
np.all(a >10)

False

In [20]:
#Are all values less than 100?
np.all(a < 100)

True

In [21]:
#Are all values in each row less than 9?
np.all(a <9 , axis=1)

array([ True,  True, False, False])