In [1]:
#import the numpy module and the csv module 
import numpy as np
import csv

In [3]:
a = np.arange(12)**2   
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121],
      dtype=int32)

In [4]:
#Suppose we want to access three different elements. We could do it like this:
a[2],a[6],a[8]

(4, 36, 64)

In [6]:
#Alternatively, we can pass a single list or array of indices to obtain the same result:
indx_1 = [2,6,8]
a[indx_1]

array([ 4, 36, 64], dtype=int32)

In [7]:
#When using fancy indexing, the shape of the result reflects the shape of the index arrays rather than the shape of the array being indexed

In [8]:
indx_2 = np.array([[2,4],[8,10]])
indx_2


array([[ 2,  4],
       [ 8, 10]])

In [9]:
a[indx_2]

array([[  4,  16],
       [ 64, 100]], dtype=int32)

In [10]:
#We can also give indexes for more than one dimension. The arrays of indices for each dimension must have the same shape.
food = np.array([["blueberry","strawberry","cherry","blackberry"],
                 ["pinenut","hazelnuts","cashewnut","coconut"],
                 ["mustard","paprika","nutmeg","clove"]])
food

array([['blueberry', 'strawberry', 'cherry', 'blackberry'],
       ['pinenut', 'hazelnuts', 'cashewnut', 'coconut'],
       ['mustard', 'paprika', 'nutmeg', 'clove']], dtype='<U10')

In [11]:
#We will now select the corner elements of this array
row = np.array([[0,0],[2,2]])
col = np.array([[0,3],[0,3]])
food[row,col]

array([['blueberry', 'blackberry'],
       ['mustard', 'clove']], dtype='<U10')

In [12]:
#Notice that the first value in the result is food[0,0], next is food[0,3] , food[2,0] and lastly food[2,3]
food[2,0]

'mustard'

In [13]:
#Modifying Values with Fancy Indexing
#Just as fancy indexing can be used to access parts of an array, it can also be used to modify parts of an array.
food[row,col] = "000000"
food

array([['000000', 'strawberry', 'cherry', '000000'],
       ['pinenut', 'hazelnuts', 'cashewnut', 'coconut'],
       ['000000', 'paprika', 'nutmeg', '000000']], dtype='<U10')

In [14]:
#We can use any assignment-type operator for this. Consider following example:
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121],
      dtype=int32)

In [17]:
indx_1

[2, 6, 8]

In [18]:
a[indx_1] = 999

In [19]:
a

array([  0,   1, 999,   9,  16,  25, 999,  49, 999,  81, 100, 121],
      dtype=int32)

In [20]:
a[indx_1] -=100
a

array([  0,   1, 899,   9,  16,  25, 899,  49, 899,  81, 100, 121],
      dtype=int32)