In [1]:
import numpy as np

In [2]:
a = np.arange(11)**2
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [3]:
a[2]

4

In [4]:
a[-2]

81

In [5]:
a[2:7]

array([ 4,  9, 16, 25, 36], dtype=int32)

In [6]:
a[2:-2]

array([ 4,  9, 16, 25, 36, 49, 64], dtype=int32)

In [7]:
a[2:]

array([  4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [8]:
a[:7]

array([ 0,  1,  4,  9, 16, 25, 36], dtype=int32)

In [9]:
a[:11:2]

array([  0,   4,  16,  36,  64, 100], dtype=int32)

In [10]:
a[::-1]

array([100,  81,  64,  49,  36,  25,  16,   9,   4,   1,   0], dtype=int32)

In [11]:
#Consider an array students, it contains the test scores in two courses of the students against their names 
#2D Array
students = np.array([['Alice','Beth','Cathy','Dorothy'],
                     [65,78,90,81],
                     [71,82,79,92]])

In [12]:
students

array([['Alice', 'Beth', 'Cathy', 'Dorothy'],
       ['65', '78', '90', '81'],
       ['71', '82', '79', '92']], dtype='<U7')

In [13]:
students[0]

array(['Alice', 'Beth', 'Cathy', 'Dorothy'], dtype='<U7')

In [14]:
students[1]

array(['65', '78', '90', '81'], dtype='<U7')

In [15]:
students[2]

array(['71', '82', '79', '92'], dtype='<U7')

In [16]:
students[0,1]

'Beth'

In [17]:
#2D Array slicing
#This will consider the rows 0 and 1, columns 2 and 3
students[0:2,2:4]

array([['Cathy', 'Dorothy'],
       ['90', '81']], dtype='<U7')

In [18]:
#All rows and column 1
students[:,1:2]

array([['Beth'],
       ['78'],
       ['82']], dtype='<U7')

In [19]:
#All rows, columns 1 and 2
students[:,1:3]

array([['Beth', 'Cathy'],
       ['78', '90'],
       ['82', '79']], dtype='<U7')

In [20]:
#All columns, rows 0 and 1
students[0:2,:]

array([['Alice', 'Beth', 'Cathy', 'Dorothy'],
       ['65', '78', '90', '81']], dtype='<U7')

In [21]:
#All rows and columns
students[:]

array([['Alice', 'Beth', 'Cathy', 'Dorothy'],
       ['65', '78', '90', '81'],
       ['71', '82', '79', '92']], dtype='<U7')

In [22]:
#The last row
students[-1,:]

array(['71', '82', '79', '92'], dtype='<U7')

In [24]:
#3rd from last to second from last row, last two columns
students[-3:-1,-2:]

array([['Cathy', 'Dorothy'],
       ['90', '81']], dtype='<U7')

In [25]:
#Select row 0 and all columns
students[0,...] 

array(['Alice', 'Beth', 'Cathy', 'Dorothy'], dtype='<U7')

In [27]:
#All rows and column 1
students[...,1]

array(['Beth', '78', '82'], dtype='<U7')

In [28]:
students[...,1].shape

(3,)

In [29]:
students[:,1:2].shape

(3, 1)