In [1]:
import numpy as np

In [4]:
#1D Arrays
a = np.arange(11)**2
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [5]:
for i in a:
    print(i**(1/2))

0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0


In [6]:
#Iterating over multidimensional arrays is done with respect to the first axis:
students = np.array([['Alice','Beth','Cathy','Dorothy'],
                     [65,78,90,81],
                     [71,82,79,92]])

In [7]:
students

array([['Alice', 'Beth', 'Cathy', 'Dorothy'],
       ['65', '78', '90', '81'],
       ['71', '82', '79', '92']], dtype='<U7')

In [8]:
for i in students:
    print('i = ', i)

i =  ['Alice' 'Beth' 'Cathy' 'Dorothy']
i =  ['65' '78' '90' '81']
i =  ['71' '82' '79' '92']


In [9]:
#Flatten a multi-dimensional array
#If one wants to perform an operation on each element in the array, one can use the flatten function which will flatten the array to a single dimension. 
#By default, the flattening will occur row-wise (also knows as C order)
for element in students.flatten():
    print(element)

Alice
Beth
Cathy
Dorothy
65
78
90
81
71
82
79
92


In [10]:
#Fortran order flattening
#To flatten a 2D array column-wise, use the Fortran order
for element in students.flatten(order='F'):
    print(element)

Alice
65
71
Beth
78
82
Cathy
90
79
Dorothy
81
92


In [11]:
#nditer
#Efficient multi-dimensional iterator object to iterate over arrays
x = np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
for i in np.nditer(x):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [17]:
#Fortran order
#This is like iterating over an array which has been flattened column-wise
for i in np.nditer(x, order = 'F'): 
    print(i)

0
4
8
1
5
9
2
6
10
3
7
11


In [18]:
#Flags
#There are a number of flags which we can pass as a list to nditer. Many of these involve setting buffering options 
#If we want iterate over each column, we can use the flag argument with value 'external_loop'
for i in np.nditer(x, order = 'F', flags = ['external_loop']): 
    print(i)


[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [19]:
#Modifying Array Values
#By default, the nditer treats the input array as a read-only object. To modify the array elements, you must specify either read-write or write-only mode. This is controlled with per-operand flags.
#Writing on a read-only array results in an error
for arr in np.nditer(x):
    arr[...] = arr * arr

ValueError: assignment destination is read-only

In [20]:
#We set the ops_flag to make the array read-write
for arr in np.nditer(x, op_flags = ['readwrite']):
    arr[...] = arr * arr
x

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])