In [ ]:
from scipy.interpolate import interp1d
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
#Use genfromtxt
#This function will load data from a text file

In [8]:
#Use genfromtxt
#This function will load data from a text file
# we will skip the header 
ages = np.genfromtxt('Ages.csv',delimiter=',',skip_header = 1)

In [ ]:
#Here, the first column is the year, the second one is median age of males and the last column is median age of females

In [7]:
ages

array([[1890. ,   26.1,   22. ],
       [1900. ,   25.9,   21.9],
       [1910. ,   25.1,   21.6],
       [1920. ,   24.6,   21.2],
       [1930. ,   24.3,   21.3],
       [1940. ,   24.3,   21.5],
       [1950. ,   22.8,   20.3],
       [1960. ,   22.8,   20.3],
       [1970. ,   23.2,   20.8],
       [1980. ,   24.7,   22. ],
       [1990. ,   26.1,   23.9],
       [2000. ,   26.8,   25.1]])

In [9]:
#Year
x = ages[:,0]
x


array([1890., 1900., 1910., 1920., 1930., 1940., 1950., 1960., 1970.,
       1980., 1990., 2000.])

In [12]:
#Median age of males
y = ages[:,1]
y


array([26.1, 25.9, 25.1, 24.6, 24.3, 24.3, 22.8, 22.8, 23.2, 24.7, 26.1,
       26.8])

In [13]:
type(x),type(y)

(numpy.ndarray, numpy.ndarray)

Scipy's interp1d function
Here, x and y are arrays of values used to approximate some function f: y = f(x). This will returns a function whose call method uses interpolation to find the value of new points.

In [14]:
f = interp1d(x, y)

In [15]:
xnew = [1896,1907,1912,1923,1929,
        1933,1939,1945,1947,1953,
        1969,1989,1992,1996,1998]

In [19]:
y

array([26.1, 25.9, 25.1, 24.6, 24.3, 24.3, 22.8, 22.8, 23.2, 24.7, 26.1,
       26.8])